### PR TITLE
Added missing "extern crate byteorder;"

### PR DESCRIPTION
**Pull request by mraof**

### CODE REVIEW

**Comment by ArtemGr** [comment]
Hey, thanks for the patch.

It builds fine, however, without the `extern crate byteorder`, where I am.
Maybe it's because I'm using "default-features = false"?

Could you test with "default-features = false" and make this `extern crate` conditional if necessary in order to avoid the "default-features = false" warning?
Or maybe add a warning-disabling attribute.

**Comment by ArtemGr** [comment]
> byteorder = { version = "0.5", optional = true } 

That might be an overkill, @mraof.
All we need to fix the warning is `#[cfg(feature="voice")]` in lib.rs.
I've fixed that in https://github.com/ArtemGr/discord-rs/commit/4d0a62a8ceecfc61c5ad75923760409f03ec5e69. Thanks for your help!

**Comment by ArtemGr** [comment]
On a second thought, your fix is a proper fix so why not. Thanks again.

**Comment by mraof** [comment]
You're welcome

**Pull request merged**
